Add the MultiMode DAE failure example
casella/FailureModes pull request #3
Opened 2020-12-10 12:51 UTC by Satinelamp

Create a new subpackage that includes the MultiMode DAE failure example. Short documentation is added to illustrate the details and give more resources about dealing with MultiMode DAE.

2020-12-11 00:31 UTC, casella requested changes
@Satinelamp, thank you very much for your contribution! 

I have two general comments

 The original intent of the library was to provide models that demonstrate possible ways models can fail because they have some issues, not because the tool is not capable to handle them. in order to encourage tool vendors to provide high-level, user-friendly error messages in those cases. 

Your MultiModeDAE is a bit borderline from this point of view. It is not clear to me if you goal is to add it so that tools can provide proper diagnostics (i.e. provide error messages such as "Multi-mode DAEs are not supported by this tool" instead of some low-level numerical error), or if it is rather to encourage tool developers to actually support such models. 

In any case, I think this is a valuable contribution.

I would only ask you to avoid committing PRs which affect files that are not directly interested, just because of whitespace changes. I guess your PR should only affect `MultiModeDAE.mo` and `package.order`. Could you please update the PR accordingly, or make a new one?

Thanks!

2020-12-11 02:36 UTC, closed without merging

2020-12-12 10:30 UTC, Satinelamp commented
@casella 
I guess the problem is caused by Dymola reformating the code. Here is a detailed discussion of this issue on [Stack Overflow](https://stackoverflow.com/questions/64497717/dymola-whitespace-and-version-control).
May I ask if you have any better solution to this problem?

2020-12-12 11:29 UTC, casella commented
This is not very user-friendly, but that's the way it is...

I would suggest that you just add and commit the `MultiModeDAE.mo` and `package.order` files to your PR branch, so you only push those two files with changes. If there are some whitespace changes in there, so be it, but at least there are no suspect changes to other package files that were not affected.

2020-12-12 11:32 UTC, Satinelamp commented
Here is the new [pull request](https://github.com/casella/FailureModes/pull/4)